# Generated by Django 2.1 on 2019-03-24 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
